### ISSUE TITLE
Still interested?

### ISSUE THREAD

**Issue by alensiljak** [kod-kristoff/ledger-rs#1]
Hi, Kristoff! Are you still interested in developing the Ledger port in Rust?
Perhaps you've already seen elsewhere, I've created an [organization](https://github.com/ledger-rs/) to gather people interested in such a project. If you have the desire and some time, hop in! Cheers

**Comment by kod-kristoff** [comment]
Hi, sounds cool, afraid that I don't have that much capacity right now. I'll see if I can help in some way later on!
Best regards

**Comment by alensiljak** [comment]
Sure! It's a broad initiative for whoever is interested. I don't expect to have working code really soon anyway. Thanks!
